title: Mike Mazzocca's Super Fun Happy Time  Blog
author: Mike Mazzocca
email: michaeljmazzocca@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Super Fun and Happy Time to be had. Also Blog.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
